In [23]:
import pandas as pd # to read and manipulate datasets

In [24]:
df2 = pd.read_csv('/Users/zacharylai/Desktop/FPL_ML/fpl_points_predictor/datasets/20:21mergedGW.csv')
df3 = pd.read_csv('/Users/zacharylai/Desktop/FPL_ML/fpl_points_predictor/datasets/21:22mergedGW.csv')
df4 = pd.read_csv('/Users/zacharylai/Desktop/FPL_ML/fpl_points_predictor/datasets/22:23mergedGW.csv')
df5 = pd.read_csv('/Users/zacharylai/Desktop/FPL_ML/fpl_points_predictor/datasets/23:24mergedGW.csv')

In [25]:
dataframes = [ df2, df3, df4, df5 ]
df = pd.concat( dataframes, ignore_index = True )

In [26]:
gk_df = df[df['position'] == 'GK']
def_df = df[df['position'] == 'DEF']
mid_df = df[df['position'] == 'MID']
fwd_df = df[df['position'] == 'FWD']


# Sort each DataFrame by 'name' and 'gameweek'
gk_df = gk_df.sort_values(by=['name', 'GW']).reset_index(drop=True)
def_df = def_df.sort_values(by=['name', 'GW']).reset_index(drop=True)
mid_df = mid_df.sort_values(by=['name', 'GW']).reset_index(drop=True)
fwd_df = fwd_df.sort_values(by=['name', 'GW']).reset_index(drop=True)

In [27]:
# gk_test_df = test_df[test_df['position'] == 'GK']
# def_test_df = test_df[test_df['position'] == 'DEF']
# mid_test_df = test_df[test_df['position'] == 'MID']
# fwd_test_df = test_df[test_df['position'] == 'FWD']


# # Sort each DataFrame by 'name' and 'gameweek'
# gk_test_df = gk_test_df.sort_values(by=['name', 'GW']).reset_index(drop=True)
# def_test_df = def_test_df.sort_values(by=['name', 'GW']).reset_index(drop=True)
# mid_test_df = mid_test_df.sort_values(by=['name', 'GW']).reset_index(drop=True)
# fwd_test_df = fwd_test_df.sort_values(by=['name', 'GW']).reset_index(drop=True)

In [28]:
# Save the datasets to CSV files
gk_df.to_csv('goalkeepers.csv', index=False)
def_df.to_csv('defenders.csv', index=False)
mid_df.to_csv('midfielders.csv', index=False)
fwd_df.to_csv('forwards.csv', index=False)

In [29]:
# # Save the datasets to CSV files
# gk_test_df.to_csv('goalkeepers_test.csv', index=False)
# def_test_df.to_csv('defenders_test.csv', index=False)
# mid_test_df.to_csv('midfielders_test.csv', index=False)
# fwd_test_df.to_csv('forwards_test.csv', index=False)

# Goalkeepers

In [ ]:
df = pd.read_csv('/Users/zacharylai/Desktop/FPL_ML/fpl_points_predictor/goalkeepers.csv')

In [ ]:
df['avg_saves'] = df.groupby('name')['saves'].expanding().mean().shift(1).reset_index(level=0, drop=True)
df['avg_ict'] = df.groupby('name')['ict_index'].expanding().mean().shift(1).reset_index(level=0, drop=True)
df['avg_pen_saves'] = df.groupby('name')['penalties_saved'].expanding().mean().shift(1).reset_index(level=0, drop=True)
df['avg_goals_conceded'] = df.groupby('name')['goals_conceded'].expanding().mean().shift(1).reset_index(level=0, drop=True)
df['avg_xP'] = df.groupby('name')['xP'].expanding().mean().shift(1).reset_index(level=0, drop=True)
df['avg_cs'] = df.groupby('name')['clean_sheets'].expanding().mean().shift(1).reset_index(level=0, drop=True)
df['avg_bps'] = df.groupby('name')['bps'].expanding().mean().shift(1).reset_index(level=0, drop=True)
df['avg_mins'] = df.groupby('name')['minutes'].expanding().mean().shift(1).reset_index(level=0, drop=True)
df['avg_x_goals_conceded'] = df.groupby('name')['expected_goals_conceded'].expanding().mean().shift(1).reset_index(level=0, drop=True)

df['total_pen_saves'] = df.groupby('name')['penalties_saved'].cumsum().shift(1).fillna(0)
df['total_cs'] = df.groupby('name')['clean_sheets'].cumsum().shift(1).fillna(0)
df['total_starts'] = df.groupby('name')['starts'].cumsum().shift(1).fillna(0)

In [ ]:
# Create a mapping from player names to categorical codes
df['name'] = df['name'].astype('category')
name_mapping = dict(enumerate(df['name'].cat.categories))
name_mapping_reverse = {v: k for k, v in name_mapping.items()}
df['name'] = df['name'].cat.codes

df['team'] = df['team'].astype('category')
df['team'] = df['team'].cat.codes

df['was_home'] = df['was_home'].astype('category')
df['was_home'] = df['was_home'].cat.codes

df = df.fillna(0)

df = df.drop(['position','total_pen_saves','was_home','team','expected_goals_conceded','penalties_saved','bonus','own_goals','minutes','saves','kickoff_time','team_a_score','team_h_score','expected_assists','expected_goal_involvements','expected_goals','transfers_in','transfers_out','transfers_balance','fixture','assists','goals_scored','ict_index','influence','creativity','threat','penalties_missed','selected','value','goals_conceded','xP','clean_sheets','element','round','red_cards','yellow_cards','starts','bps','total_pen_saves','total_cs'],axis=1)

In [ ]:
df = pd.DataFrame(df)
y = df['total_points']
X = df.drop(['total_points'],axis=1)

In [31]:
test_set = df.iloc[-len(df5):].reset_index(drop=True)
train_set = df.iloc[:-len(df5)].reset_index(drop=True)

In [32]:
test_set

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,transfers_out,value,was_home,yellow_cards,GW,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts
0,Malang Sarr,DEF,Chelsea,1.0,0,0,0,0,0.0,501,...,853,49,False,0,36,NaN,NaN,NaN,NaN,NaN
1,Willy Caballero,GK,Southampton,0.5,0,0,0,0,0.0,641,...,130,42,False,0,36,NaN,NaN,NaN,NaN,NaN
2,Douglas Luiz Soares de Paulo,MID,Aston Villa,6.5,0,0,10,0,2.8,50,...,5951,43,False,0,36,NaN,NaN,NaN,NaN,NaN
3,Douglas Luiz Soares de Paulo,MID,Aston Villa,6.5,0,2,31,0,16.1,50,...,5951,43,True,0,36,NaN,NaN,NaN,NaN,NaN
4,Sergi Canós,MID,Brentford,0.0,0,0,0,0,0.0,81,...,1271,55,True,0,36,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28855,Oliver Skipp,MID,Spurs,2.0,0,0,16,0,0.0,441,...,642,43,False,0,38,0.01,0.01,0.0,1.5,1.0
28856,Ryan Sessegnon,DEF,Spurs,0.0,0,0,0,0,0.0,436,...,190,44,False,0,38,0.00,0.00,0.0,0.0,0.0
28857,Ashley Young,DEF,Aston Villa,1.0,0,0,0,0,0.0,538,...,2668,43,True,0,38,0.00,0.00,0.0,0.0,0.0
28858,Jeremy Sarmiento Morante,MID,Brighton,0.0,0,0,0,0,0.0,119,...,39,45,False,0,38,0.00,0.00,0.0,0.0,0.0
28859,Philip Billing,MID,Bournemouth,1.1,0,0,15,0,0.0,70,...,19097,50,False,0,38,0.04,0.04,0.0,1.0,1.0

In [33]:
train_set

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,transfers_out,value,was_home,yellow_cards,GW,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,starts
0,Aaron Connolly,FWD,Brighton,0.5,0,0,-3,0,0.3,78,...,0,55,True,0,1,NaN,NaN,NaN,NaN,NaN
1,Aaron Cresswell,DEF,West Ham,2.1,0,0,11,0,11.2,435,...,0,50,True,0,1,NaN,NaN,NaN,NaN,NaN
2,Aaron Mooy,MID,Brighton,0.0,0,0,0,0,0.0,60,...,0,50,True,0,1,NaN,NaN,NaN,NaN,NaN
3,Aaron Ramsdale,GK,Sheffield Utd,2.5,0,0,12,0,0.0,483,...,0,50,True,0,1,NaN,NaN,NaN,NaN,NaN
4,Abdoulaye Doucouré,MID,Everton,1.3,0,0,20,1,44.6,512,...,0,55,False,0,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47452,Salah-Eddine Oulad M'hand,MID,Arsenal,0.5,0,0,0,0,0.0,693,...,15,45,False,0,36,NaN,NaN,NaN,NaN,NaN
47453,Jamaal Lascelles,DEF,Newcastle,0.6,0,0,10,0,0.3,299,...,469,44,False,0,36,NaN,NaN,NaN,NaN,NaN
47454,Darren Randolph,GK,West Ham,0.5,0,0,0,0,0.0,407,...,82,43,False,0,36,NaN,NaN,NaN,NaN,NaN
47455,Mads Bech Sørensen,DEF,Brentford,3.0,0,0,19,1,0.1,90,...,68,43,True,0,36,NaN,NaN,NaN,NaN,NaN
47456,Malang Sarr,DEF,Chelsea,1.0,0,0,3,0,0.0,501,...,853,49,True,0,36,NaN,NaN,NaN,NaN,NaN